### ISSUE TITLE
Docker image build

### ISSUE THREAD

**Issue by gylfirst** [Zalk0/ChouetteBot-discord#12]
Docker image cant build currently:
- on i386 platform

Causes:
- Cargo is not installed

**Comment by gylfirst** [comment]
After #13, we add to the bug list:
- ppc64le

**Comment by Zalk0** [comment]
Only build docker images for amd64, armv6 and armv7 because those are common platforms and wheels are available so it's easy to build

**Comment by Zalk0** [comment]
Now building images for arm64 :tada:

**Comment by gylfirst** [comment]
Close the issue for now
Maybe we will add more in future
